# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lanyon
tagline:             'Veille technologique'
description:         'Avancées technologiques de la Blockchain'
url:                 http://lanyon.getpoole.com
baseurl:             '/Veille'
paginate:            5

# About/contact
author:
  name:              Mehdi ElYaakabi
  url:               https://twitter.com/@mehdi-yaak
  email:             mehdi.elyaakabi@gmail.com

# Custom vars
version:             1.0.0
